-- DROP CONSTRAINT
ALTER TABLE SARTEN_QUE_LADRA.ProductoXRubro DROP CONSTRAINT fk_productorubro_producto;
ALTER TABLE SARTEN_QUE_LADRA.ProductoXRubro DROP CONSTRAINT fk_productorubro_rubro;

ALTER TABLE SARTEN_QUE_LADRA.SubrubroXRubro DROP CONSTRAINT IF EXISTS fk_subrubroxrubro_rubro_id;
ALTER TABLE SARTEN_QUE_LADRA.SubrubroXRubro DROP CONSTRAINT IF EXISTS fk_subrubroxrubro_subrubro_id;

ALTER TABLE SARTEN_QUE_LADRA.MarcaXProducto DROP CONSTRAINT IF EXISTS fk_marcaproducto_producto;
ALTER TABLE SARTEN_QUE_LADRA.MarcaXProducto DROP CONSTRAINT IF EXISTS fk_marcaproducto_marca;

ALTER TABLE SARTEN_QUE_LADRA.ModeloXProducto DROP CONSTRAINT IF EXISTS fk_modeloproducto_producto;
ALTER TABLE SARTEN_QUE_LADRA.ModeloXProducto DROP CONSTRAINT IF EXISTS fk_modeloproducto_modelo;

ALTER TABLE SARTEN_QUE_LADRA.ProductoXSubrubro DROP CONSTRAINT IF EXISTS fk_productosubrubro_producto;
ALTER TABLE SARTEN_QUE_LADRA.ProductoXSubrubro DROP CONSTRAINT IF EXISTS fk_productosubrubro_subrubro;

ALTER TABLE SARTEN_QUE_LADRA.Localidad DROP CONSTRAINT IF EXISTS fk_localidad_provincia;

ALTER TABLE SARTEN_QUE_LADRA.Domicilio DROP CONSTRAINT IF EXISTS fk_domicilio_localidad;

ALTER TABLE SARTEN_QUE_LADRA.DomicilioXUsuario DROP CONSTRAINT IF EXISTS fk_domiciliousuario_usuario;
ALTER TABLE SARTEN_QUE_LADRA.DomicilioXUsuario DROP CONSTRAINT IF EXISTS fk_domiciliousuario_domicilio;

ALTER TABLE SARTEN_QUE_LADRA.Cliente DROP CONSTRAINT IF EXISTS fk_cliente_usuario;

ALTER TABLE SARTEN_QUE_LADRA.Vendedor DROP CONSTRAINT IF EXISTS fk_vendedor_usuario;

ALTER TABLE SARTEN_QUE_LADRA.Envio DROP CONSTRAINT IF EXISTS fk_envio_venta;
ALTER TABLE SARTEN_QUE_LADRA.Envio DROP CONSTRAINT IF EXISTS fk_envio_domicilio;
ALTER TABLE SARTEN_QUE_LADRA.Envio DROP CONSTRAINT IF EXISTS fk_envio_tipo_envio;

ALTER TABLE SARTEN_QUE_LADRA.Factura DROP CONSTRAINT IF EXISTS fk_factura_vendedor;

ALTER TABLE SARTEN_QUE_LADRA.Almacen DROP CONSTRAINT IF EXISTS fk_almacen_localidad;

ALTER TABLE SARTEN_QUE_LADRA.Publicacion DROP CONSTRAINT IF EXISTS fk_publicacion_producto;
ALTER TABLE SARTEN_QUE_LADRA.Publicacion DROP CONSTRAINT IF EXISTS fk_publicacion_vendedor;
ALTER TABLE SARTEN_QUE_LADRA.Publicacion DROP CONSTRAINT IF EXISTS fk_publicacion_almacen;

ALTER TABLE SARTEN_QUE_LADRA.DetalleFactura DROP CONSTRAINT IF EXISTS fk_detallefactura_publicacion;
ALTER TABLE SARTEN_QUE_LADRA.DetalleFactura DROP CONSTRAINT IF EXISTS fk_detallefactura_concepto;
ALTER TABLE SARTEN_QUE_LADRA.DetalleFactura DROP CONSTRAINT IF EXISTS fk_detallefactura_factura;

ALTER TABLE SARTEN_QUE_LADRA.DetalleVenta DROP CONSTRAINT IF EXISTS fk_detalleventa_venta;
ALTER TABLE SARTEN_QUE_LADRA.DetalleVenta DROP CONSTRAINT IF EXISTS fk_detalleventa_publicacion;

ALTER TABLE SARTEN_QUE_LADRA.Pago DROP CONSTRAINT IF EXISTS fk_pago_venta;

ALTER TABLE SARTEN_QUE_LADRA.MedioXPago DROP CONSTRAINT IF EXISTS fk_mediopago_pago;
ALTER TABLE SARTEN_QUE_LADRA.MedioXPago DROP CONSTRAINT IF EXISTS fk_mediopago_mediodepago;
ALTER TABLE SARTEN_QUE_LADRA.MedioXPago DROP CONSTRAINT IF EXISTS fk_mediopago_detallepago;

ALTER TABLE SARTEN_QUE_LADRA.MedioPago DROP CONSTRAINT IF EXISTS fk_mediopago_tipomediopago;

ALTER TABLE SARTEN_QUE_LADRA.Venta DROP CONSTRAINT IF EXISTS fk_venta_cliente;

-- DROP DE TODAS LAS TABLAS
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Almacen;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Cliente;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Concepto;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.DetallePago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.DetalleFactura;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.DetalleVenta;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Domicilio;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.DomicilioXUsuario;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Envio;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Factura;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Localidad;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Marca;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.MarcaXProducto;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.MedioPago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.MedioXPago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Modelo;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.ModeloXProducto;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Pago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Producto;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.ProductoXSubrubro;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Publicacion;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Provincia;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.TipoMedioPago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.TipoEnvio;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Usuario;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Vendedor;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Venta;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Rubro;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Subrubro;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.SubrubroXRubro;

-- DROP PROCEDURES
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_PROVINCIA;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_LOCALIDAD;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_DOMICILIO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_MARCA;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_MODELO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_ALMACEN;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_PRODUCTO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_MARCAXPRODUCTO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_MODELOXPRODUCTO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_TIPO_ENVIO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_USUARIO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_CLIENTE;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_VENDEDOR;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_VENTA;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_ENVIO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_PUBLICACION;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_DETALLE_FACTURA;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_DOMICILIOXUSUARIO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_CONCEPTO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_FACTURA;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_DETALLE_VENTA;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_RUBRO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_SUBRUBROXRUBRO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_SUBRUBRO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_PRODUCTOXSUBRUBRO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_PRODUCTOXRUBRO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_DETALLE_PAGO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_TIPO_MEDIO_PAGO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_MEDIO_PAGO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_PAGO;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.MIGRAR_MEDIOXPAGO;

-- DROP SCHEMA
--DROP SCHEMA IF EXISTS SARTEN_QUE_LADRA;

-- QUERY PARA VER TODAS LAS FK PRESENTES
SELECT 
    fk.name AS FK_name, 
    tp.name AS Table_name 
FROM sys.foreign_keys AS fk
INNER JOIN sys.tables AS tp ON fk.parent_object_id = tp.object_id
WHERE tp.name IN ('Almacen', 'Cliente', 'Concepto', 'DetalleFactura', 'DetallePago', 'DetalleVenta', 
'Domicilio', 
'DomicilioXUsuario', 'Envio', 'Factura', 
'Localidad', 'Marca', 
'MarcaXProducto', 'MedioPago', 'MedioXPago', 'Modelo', 'ModeloXProducto', 'Pago', 'Producto', 'ProductoXSubrubro',
'Publicacion', 
'Provincia', 'Rubro', 'Subrubro', 'SubrubroXRubro', 'TipoEnvio', 'TipoMedioPago', 'Usuario', 
'Vendedor', 
'Venta');

-- QUERY PARA VER TODAS LAS TABLAS EXISTENTES ENTRE LA LISTA
SELECT * FROM sys.tables WHERE name IN ('Almacen', 'Cliente', 'Concepto', 'DetalleFactura', 'DetallePago', 'DetalleVenta', 
'Domicilio', 'DomicilioXUsuario', 'Envio', 'Factura', 'Localidad', 'Marca', 
'MarcaXProducto', 'MedioPago', 'MedioXPago', 'Modelo', 'ModeloXProducto', 'Pago', 'Producto', 'ProductoXSubrubro',
'Publicacion', 'Provincia', 'Rubro', 'Subrubro', 'SubrubroXRubro', 'TipoEnvio', 'TipoMedioPago', 'Usuario', 
'Vendedor', 
'Venta');

-- QUERY PARA VER TODAS LAS PROCEDURES
SELECT * FROM sys.procedures;
