-- DROP DE TODAS LAS CONSTRAINT
ALTER TABLE SARTEN_QUE_LADRA.BI_Localidad
DROP CONSTRAINT fk_bilocalidad_provincia;

SELECT * FROM sys.tables 
WHERE name LIKE 'BI%' OR name LIKE 'Hechos%';

-- DROP DE TODAS LAS TABLE
DROP TABLE SARTEN_QUE_LADRA.BI_Localidad;
DROP TABLE SARTEN_QUE_LADRA.BI_Provincia;

DROP FUNCTION SARTEN_QUE_LADRA.BI_Select_Localidad_Cliente;

SELECT name 
FROM sys.procedures
WHERE name LIKE 'BI%';

-- DROP DE TODAS LAS PROCEDURES
DROP PROCEDURE SARTEN_QUE_LADRA.BI_Migrar_Provincia;
DROP PROCEDURE SARTEN_QUE_LADRA.BI_Migrar_Localidad;
