-- ============================== -- 
--	   FOREIGN KEYS	          --
-- ============================== --

ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Localidad_Cliente;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Tiempo;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Medio_De_Pago;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Tipo_Medio_De_Pago;

ALTER TABLE SARTEN_QUE_LADRA.BI_HECHOS_ENVIO DROP CONSTRAINT FK_BI_HechosEnvio_LocCliente;
ALTER TABLE SARTEN_QUE_LADRA.BI_HECHOS_ENVIO DROP CONSTRAINT FK_BI_HechosEnvio_ProvinciaAlmacen;
ALTER TABLE SARTEN_QUE_LADRA.BI_HECHOS_ENVIO DROP CONSTRAINT FK_BI_HechosEnvio_Tiempo;
ALTER TABLE SARTEN_QUE_LADRA.BI_Localidad DROP CONSTRAINT FK_BI_Localidad_Provincia;

ALTER TABLE SARTEN_QUE_LADRA.BI_HECHOS_FACTURA DROP CONSTRAINT FK_BI_HECHOS_FACTURA_PROVINCIA;
ALTER TABLE SARTEN_QUE_LADRA.BI_HECHOS_FACTURA DROP CONSTRAINT FK_BI_HECHOS_FACTURA_Tiempo;
ALTER TABLE SARTEN_QUE_LADRA.BI_HECHOS_FACTURA DROP CONSTRAINT FK_BI_HECHOS_FACTURA_concepto;

ALTER TABLE SARTEN_QUE_LADRA.Hechos_Venta DROP CONSTRAINT fk_hechos_venta_provincia;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Venta DROP CONSTRAINT fk_hechos_venta_rango_etario;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Venta DROP CONSTRAINT fk_hechos_venta_tiempo;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Venta DROP CONSTRAINT fk_hechos_venta_rubro;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Venta DROP CONSTRAINT fk_hechos_venta_localidad;

-- ============================== -- 
--		TABLES	          --
-- ============================== --

DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Hechos_Venta;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Rubro;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Subrubro;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Rango_Etario;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Rango_Horario;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Tiempo;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Localidad;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Provincia;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Medio_De_Pago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Tipo_Medio_De_Pago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_Tipo_envio;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_CONCEPTO
  
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.Hechos_Pago;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_HECHOS_ENVIO;
DROP TABLE IF EXISTS SARTEN_QUE_LADRA.BI_HECHOS_FACTURA;

-- ============================== -- 
--			FUNCTIONS	          --
-- ============================== --

DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.BI_Select_Localidad_Cliente_Segun_Cantidad_De_Domicilios;
DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.BI_Select_Localidad_Cliente;
DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.BI_Cantidad_De_Domicilios;
DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.BI_Select_Tiempo;
DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.BI_Select_Provincia_Almacen;
DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.BI_Select_Provincia_Vendedor;
DROP FUNCTION IF EXISTS SARTEN_QUE_LADRA.ENVIADOS_A_TIEMPO

-- ============================== -- 
--	    PROCEDURES	          --
-- ============================== --
  
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Provincia;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Concepto;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Localidad;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Tiempo;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Medio_De_Pago;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Tipo_Medio_De_Pago;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Pago;
DROP PROCEDURE IF EXISTS SARTEN_QUE_LADRA.BI_Migrar_Hechos_Factura;

-- ============================== -- 
--		VIEWS	          --
-- ============================== --

DROP VIEW IF EXISTS SARTEN_QUE_LADRA.LOCALIDADES_MAYOR_IMPORTE_CUOTAS;

-- QUERYS PARA VALIDAR OBJETOS

-- TABLAS
SELECT 
	  TABLE_SCHEMA AS Esquema,
    TABLE_NAME AS Tabla
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- FOREIGN KEYS
SELECT fk.name AS Nombre_Clave_Foranea
FROM sys.foreign_keys AS fk
  
-- VIEWS
SELECT TABLE_SCHEMA AS Esquema, TABLE_NAME AS Vista
FROM INFORMATION_SCHEMA.VIEWS
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- FUNCIONES
SELECT ROUTINE_SCHEMA AS Esquema, ROUTINE_NAME AS Funcion
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'FUNCTION'
ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;

-- PROCEDIMIENTOS
SELECT ROUTINE_SCHEMA AS Esquema, ROUTINE_NAME AS Procedimiento
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'
ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;




