ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Localidad_Cliente;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Tiempo;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Medio_De_Pago;
ALTER TABLE SARTEN_QUE_LADRA.Hechos_Pago DROP CONSTRAINT FK_Hechos_Pago_Tipo_Medio_De_Pago;

-- Luego eliminamos las tablas
DROP TABLE SARTEN_QUE_LADRA.Hechos_Pago;
DROP TABLE SARTEN_QUE_LADRA.BI_Medio_De_Pago;
DROP TABLE SARTEN_QUE_LADRA.BI_Tipo_Medio_De_Pago;
